name: AzureSpringApps
on: push
env:
  ASC_PACKAGE_PATH: src/spring-petclinic-admin-server
  AZURE_SUBSCRIPTION: f7f7f0b4-1299-429b-8927-12f2c5881db2

jobs:
  deploy_to_production:
    runs-on: ubuntu-latest
    name: deploy to production with artifact
    steps:
      - name: Checkout Github Action
        uses: actions/checkout@v2
        
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: maven build, clean
        run: |
          cd ${{ github.workspace }}/src
          mvn clean package -DskipTests
          cp ${{ github.workspace }}/src/spring-petclinic-admin-server/target/spring-petclinic-admin-server-3.0.2.jar spring-petclinic-admin-server-3.0.2.jar
